# Experiment No 20

## Solving Matrices

In [14]:
from scipy import linalg
import numpy as np
print("Determinant of 2x2 Matrix")
a=[4,5]
b=[3,2]
print(a,b,sep="\n")
arr_2d = np.array([a,b])
linalg.det( arr_2d )

Determinant of 2x2 Square Matrix
[4, 5]
[3, 2]


-7.0

In [16]:
from scipy import linalg
import numpy as np
print("Determinant of 3x3 Matrix")
a=[5,3,9]
b=[0,6,4]
c=[2,8,7]
print(a,b,c,sep="\n")
arr_3d = np.array([a,b,c])
linalg.det( arr_3d )

Determinant of 3x3 Square Matrix
[5, 3, 9]
[0, 6, 4]
[2, 8, 7]


-33.99999999999999

In [25]:
from scipy import linalg
import numpy as np
print("Eigen values & Eigen Vectors of 2x2 matrix")
a=[7,0]
b=[2,9]
print(a,b,sep="\n")
arr_2d = np.array([a,b])
eigenValue, eigenVector = linalg.eig(arr_2d)
print("\nEigens Values: ", eigenValue)
print("\nEigens Vectors: ", eigenVector,sep="\n")

Eigen values & Eigen Vectors of 2x2 matrix
[7, 0]
[2, 9]

Eigens Values:  [9.+0.j 7.+0.j]

Eigens Vectors: 
[[ 0.          0.70710678]
 [ 1.         -0.70710678]]


In [28]:
from scipy import linalg
import numpy as np
print("Eigen values & Eigen Vectors of 3x3 matrix")
a=list(map(int,input("Enter 3 values separated with space: ").split()))
b=list(map(int,input("Enter 3 values separated with space: ").split()))
c=list(map(int,input("Enter 3 values separated with space: ").split()))
print(a,b,c,sep="\n")
arr_3d = np.array([a,b,c])
eigenValue, eigenVector = linalg.eig(arr_3d)
print("\nEigens Values: ", eigenValue)
print("\nEigens Vectors: ", eigenVector,sep="\n")

Eigen values & Eigen Vectors of 3x3 matrix
Enter 3 values separated with space: 7 0 0
Enter 3 values separated with space: 5 3 0
Enter 3 values separated with space: 6 1 4
[7, 0, 0]
[5, 3, 0]
[6, 1, 4]

Eigens Values:  [4.+0.j 3.+0.j 7.+0.j]

Eigens Vectors: 
[[ 0.          0.          0.34497574]
 [ 0.          0.70710678  0.43121968]
 [ 1.         -0.70710678  0.83369138]]


## Solve Equations

### x + 3y + 5z = 10
### 2x + 5y + z = 8
### 2x + 3y + 8z = 3

In [10]:
from scipy import linalg
import numpy as np
equation = np.array([[1,3,5],[2,5,1],[2,3,8]])
solution = np.array([[10],[8],[3]])
roots = linalg.solve(equation,solution)
print(roots)

[[-9.28]
 [ 5.16]
 [ 0.76]]
